name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        # Build for multiple architectures for testing
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ha-addon-glutun:test \
          --load .
        
    - name: Test Docker image
      run: |
        # Test that the image can be created and basic structure is correct
        docker run --rm ha-addon-glutun:test ls -la /usr/local/bin/
        docker run --rm ha-addon-glutun:test which gluetun
        docker run --rm ha-addon-glutun:test which python3
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: |
          Dockerfile.local
          config.yaml
          run
        retention-days: 1 